apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImJHRmljbUZqWVRwQlVsTlBYMGR5ZFhCdk5RPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQ==
  type: kubernetes.io/dockerconfigjson
