apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJpbmRleC5kb2NrZXIuaW8vdjEvIjp7InVzZXJuYW1lIjoibGFicmFjYSIsInBhc3N3b3JkIjoiQVJTT19HcnVwbzUiLCJlbWFpbCI6ImFuZ2VsbGFicmFjYUBnbWFpbC5jb20iLCJhdXRoIjogImJHRmljbUZqWVRwQlVsTlBYMGR5ZFhCdk5RPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQ==
  type: kubernetes.io/dockerconfigjson
