apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: nginx.warso.es
      http:
        paths:
          - backend:
              serviceName: nginx-nodeport
              servicePort: 80
