apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: kibana
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana:5.3.1
        command:
        - /bin/bash
        - -c
        - '/usr/share/kibana/bin/kibana-plugin remove x-pack && /usr/local/bin/kibana-docker'
        imagePullPolicy: Always
        # resources:
        #   # keep request = limit to keep this container in guaranteed class
        #   limits:
        #     cpu: 1000m
        #     memory: 1024Mi
        #   requests:
        #     cpu: 250m
        #     memory: 256Mi
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config
      volumes:
      - name: "config"
        configMap:
          name: kibana-config
