apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: labraca/nginxbueno:v0
        command: ["sh","-c","echo $HOSTNAME >> /home/ip.txt"]
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
