apiVersion: v1
data:
  password: d29yZHByZXNzUGFzcw==
kind: Secret
metadata:
  creationTimestamp: "2021-01-13T22:20:41Z"
  name: mysql-pass
  namespace: default
  resourceVersion: "141558"
  selfLink: /api/v1/namespaces/default/secrets/mysql-pass
  uid: c62c1885-179e-43c3-9743-a247125b4cd5
type: Opaque
