apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
     - http:
        paths: 
        - path: /web
          backend:
            serviceName: nginx-lb
            servicePort: 80
        - path: /filezilla
          backend:
            serviceName: filezilla-nodeport
            servicePort: 80
        - path: /wordpress
          backend:
            serviceName: wordpress-lb
            servicePort: 80
